[build]
  base = "/frontend"
  publish = "/build"
  command = "CI= npm run build"
  node_bundler = "esbuild"
  functions = "../backend/functions"

[[redirects]]
  from = "*"
  to = "/.netlify/functions/app"
  status = 200
