[build]
  publish = "/frontend/build"
  command = "npm run build"
  node_bundler = "esbuild"
  functions = "/backend/functions"

[[redirects]]
  from = "*"
  to = "/.netlify/functions/app"
  status = 200
