exports.fakeUsers = [
  {
    firstName: 'Reynold',
    lastName: 'Spinka',
    gender: 'Male',
    avatar: 'https://picsum.photos/id/676/480/480',
    username: 'reynoldspinka',
    email: 'reynoldspinka@fancybook.com',
    password: 'reynoldspinka',
    _id: '6306d7ae5a4d17eafd1fa722',
  },
  {
    firstName: 'Elnora',
    lastName: 'Steuber',
    gender: 'Female',
    avatar: 'https://picsum.photos/id/146/480/480',
    username: 'elnorasteuber',
    email: 'elnorasteuber@fancybook.com',
    password: 'elnorasteuber',
    _id: '6306d7ae5a4d17eafd1fa723',
  },
  {
    firstName: 'Tiffany',
    lastName: 'Simonis',
    gender: 'Male',
    avatar: 'https://picsum.photos/id/382/480/480',
    username: 'tiffanysimonis',
    email: 'tiffanysimonis@fancybook.com',
    password: 'tiffanysimonis',
    _id: '6306d7ae5a4d17eafd1fa724',
  },
  {
    firstName: 'Madalyn',
    lastName: 'Dickinson',
    gender: 'Male',
    avatar: 'https://picsum.photos/id/271/480/480',
    username: 'madalyndickinson',
    email: 'madalyndickinson@fancybook.com',
    password: 'madalyndickinson',
    _id: '6306d7ae5a4d17eafd1fa725',
  },
  {
    firstName: 'Christop',
    lastName: 'Casper',
    gender: 'Male',
    avatar: 'https://picsum.photos/id/578/480/480',
    username: 'christopcasper',
    email: 'christopcasper@fancybook.com',
    password: 'christopcasper',
    _id: '6306d7ae5a4d17eafd1fa726',
  },
  {
    firstName: 'Alvis',
    lastName: 'Volkman',
    gender: 'Male',
    avatar: 'https://picsum.photos/id/188/480/480',
    username: 'alvisvolkman',
    email: 'alvisvolkman@fancybook.com',
    password: 'alvisvolkman',
    _id: '6306d7ae5a4d17eafd1fa727',
  },
  {
    firstName: 'Kacie',
    lastName: 'Hilll',
    gender: 'Female',
    avatar: 'https://picsum.photos/id/799/480/480',
    username: 'kaciehilll',
    email: 'kaciehilll@fancybook.com',
    password: 'kaciehilll',
    _id: '6306d7ae5a4d17eafd1fa728',
  },
  {
    firstName: 'Autumn',
    lastName: 'Jast',
    gender: 'Male',
    avatar: 'https://picsum.photos/id/306/480/480',
    username: 'autumnjast',
    email: 'autumnjast@fancybook.com',
    password: 'autumnjast',
    _id: '6306d7ae5a4d17eafd1fa729',
  },
  {
    firstName: 'Nedra',
    lastName: 'Hamill',
    gender: 'Male',
    avatar: 'https://picsum.photos/id/233/480/480',
    username: 'nedrahamill',
    email: 'nedrahamill@fancybook.com',
    password: 'nedrahamill',
    _id: '6306d7ae5a4d17eafd1fa72a',
  },
  {
    firstName: 'Johnny',
    lastName: 'Murphy',
    gender: 'Female',
    avatar: 'https://picsum.photos/id/158/480/480',
    username: 'johnnymurphy',
    email: 'johnnymurphy@fancybook.com',
    password: 'johnnymurphy',
    _id: '6306d7ae5a4d17eafd1fa72b',
  },
];
